[versions]

androidGradle = "7.0.2"
androidSwissKnife = "44f27ec213"
androidX-core-splashscreen = "1.0.0-alpha02"
androidX-datastore = "1.0.0"
androidX-room = "2.3.0"
androidX-testEspresso = "3.4.0"
androidX-testJunit = "1.1.3"
accompanist = "0.19.0"
coil = "1.3.2"
compose-constraintLayout = "1.0.0-rc01"
compose-core = "1.0.3"
compose-navigation = "2.4.0-alpha10"
compose-viewModel = "1.0.0-alpha07"
dependencyUpdates = "0.39.0"
detekt = "1.18.1"
firebaseCrashlytics = "18.2.1"
firebaseCrashlyticsPlugin = "2.7.1"
flipper = "0.110.0"
googleServices = "4.3.10"
junit = "4.13.2"
koin = "3.1.2"
kotlin-core = "1.5.30"
kotlin-coroutines = "1.5.2"
kotlin-serialization = "1.3.0"
leakcanary = "2.7"
ok2CurlInterceptor = "0.7.0"
okIo = "2.10.0"
okhttp3 = "4.9.2"
once = "1.3.1"
retrofit2-core = "2.9.0"
retrofit2-jsonSerializer = "0.8.0"
snapshotPublisher = "2.3.0-AGP7.0"
soloader = "0.10.1"
store = "4.0.2-KT15"
timber = "5.0.1"

[libraries]

swissKnife-core = { module = "com.github.xmartlabs.AndroidSwissKnife:swissknife-core", version.ref = "androidSwissKnife" }

accompanist-systemuicontroller = { module =  "com.google.accompanist:accompanist-systemuicontroller" , version.ref = "accompanist" }
accompanist-insets = { module =  "com.google.accompanist:accompanist-insets" , version.ref = "accompanist" }

androidX-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidX-core-splashscreen" }
androidX-dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidX-datastore" }
androidX-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidX-room" }
androidX-room-core = { module = "androidx.room:room-ktx", version.ref = "androidX-room" }

androidX-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidX-testEspresso" }
androidX-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidX-testJunit" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
okIo = { module = "com.squareup.okio:okio", version.ref = "okIo" }
once = { module = "com.jonathanfinerty.once:once", version.ref = "once" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-core" }
compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraintLayout" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-core" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-core" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-core" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-core" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-core" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewModel" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

flipper-core = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-leakCanary = { module = "com.facebook.flipper:flipper-leakcanary2-plugin", version.ref = "flipper" }
flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }

firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }

junit = { module = "junit:junit", version.ref = "junit" }

koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-core" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

okhttp3-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-logginInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
okhttp3-ok2CurlInterceptor = { module = "com.github.mrmike:ok2curl", version.ref = "ok2CurlInterceptor" }
okhttp3-urlConnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp3" }

retrofit2-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2-core" }
retrofit2-jsonSerializer = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-jsonSerializer" }
store = { module = "com.dropbox.mobile.store:store4", version.ref = "store" }

## Plugin dependencies
gp-androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
gp-dependencyUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "dependencyUpdates" }
gp-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gp-firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
gp-googleServices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gp-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gp-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-core" }
gp-snapshotPublisher = { module = "com.github.xmartlabs:android-snapshot-publisher", version.ref = "snapshotPublisher" }

[bundles]

accompanist = ["accompanist-systemuicontroller", "accompanist-insets"]
androidSwissKnife = ["swissKnife-core"]
androidXTest = ["androidX-test-espresso", "androidX-test-junit"]
compose = ["compose-compiler", "compose-constraintLayout", "compose-foundation", "compose-material",
    "compose-navigation", "compose-runtime", "compose-tooling", "compose-ui", "compose-viewmodel"]
flipper = ["flipper-core", "flipper-leakCanary", "flipper-network", "soloader"]
kotlin = ["kotlin-core", "kotlin-serialization", "kotlin-coroutines"]
networking-core = ["okhttp3-core", "okhttp3-urlConnection", "okIo", "retrofit2-core", "retrofit2-jsonSerializer"]
networking-debug = ["okhttp3-logginInterceptor", "okhttp3-ok2CurlInterceptor"]
