[versions]

androidSwissKnife = "44f27ec213"
androidXRoom = "2.3.0"
coil = "1.2.0"
compose = "1.0.0-beta05"
composeConstraintLayout = "1.0.0-alpha05"
composeMaterial = "1.0.0-beta05"
composeNavigation = "1.0.0-alpha10"
composeViewModel = "1.0.0-alpha04"
firebaseCrashlytics = "17.4.0"
koin = "3.0.1"
kotlin = "1.4.32"
kotlinCoroutines = "1.4.3"
ok2CurlInterceptor = "0.7.0"
okhttp3 = "4.9.1"
okIo = "2.10.0"
once = "1.3.0"
stetho = "1b2c025a14"
timber = "4.7.1"

[libraries]

swissKnife-core = {module = "com.github.xmartlabs.AndroidSwissKnife:swissknife-core", version.ref = "androidSwissKnife"}
swissKnife-dataStore = {module = "com.github.xmartlabs.AndroidSwissKnife:swissknife-datastore", version.ref = "androidSwissKnife"}

androidXRoom-compiler = {module = "androidx.room:room-compiler", version.ref = "androidXRoom"}
androidXRoom-coreKtx = {module = "androidx.room:room-ktx", version.ref = "androidXRoom"}

coil = {module = "io.coil-kt:coil", version.ref = "coil"}
okIo = {module = "com.squareup.okio:okio", version.ref = "okIo"}
once = {module = "com.jonathanfinerty.once:once", version.ref = "once"}
stetho = {module = "com.github.mathroule.stetho:stetho", version.ref = "stetho"}
timber = {module = "com.jakewharton.timber:timber", version.ref = "timber"}

compose-compiler = {module ="androidx.compose.compiler:compiler", version.ref = "compose"}
compose-constraintLayout = {module ="androidx.constraintlayout:constraintlayout-compose", version.ref = "composeConstraintLayout"}
compose-foundation = {module ="androidx.compose.foundation:foundation", version.ref = "compose"}
compose-material = {module ="androidx.compose.material:material", version.ref = "composeMaterial"}
compose-navigation = {module ="androidx.navigation:navigation-compose", version.ref = "composeNavigation"}
compose-runtime = {module ="androidx.compose.runtime:runtime", version.ref = "compose"}
compose-tooling = {module ="androidx.compose.ui:ui-tooling", version.ref = "compose"}
compose-ui = {module ="androidx.compose.ui:ui", version.ref = "compose"}
compose-viewmodel = {module ="androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewModel"}

firebase-crashlytics = {module ="com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics"}

koin-compose = {module = "io.insert-koin:koin-androidx-compose", version.ref = "koin"}

kotlin-core = {module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin"}
kotlin-coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines"}

okhttp3-core = {module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3"}
okhttp3-logginInterceptor = {module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3"}
okhttp3-ok2CurlInterceptor = {module = "com.github.mrmike:ok2curl", version.ref = "ok2CurlInterceptor"}
okhttp3-urlConnection = {module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp3"}
okhttp3-stetho = {module = "com.github.mathroule.stetho:stetho-okhttp3", version.ref = "stetho"}

[bundles]

androidSwissKnife = ["swissKnife-core", "swissKnife-dataStore"]
compose = ["compose-compiler", "compose-constraintLayout", "compose-foundation", "compose-material",
  "compose-navigation", "compose-runtime", "compose-tooling", "compose-ui", "compose-viewmodel"]
kotlin = ["kotlin-core", "kotlin-coroutines"]
okhttp3 = ["okhttp3-core", "okhttp3-logginInterceptor", "okhttp3-ok2CurlInterceptor", "okhttp3-urlConnection",
  "okhttp3-stetho"]
utils = ["coil", "okIo", "once", "stetho"]
